name: ng_admin
description: Admin Template based on Angular Dart
version: 0.0.1+7
homepage: https://github.com/wowsomeco/ng_dart_admin

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0  
  angular_router: ^2.0.0-alpha+22
  angular_forms: ^2.1.2
  js: ^0.6.1+1  

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0    