include: package:pedantic/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: false

analyzer:
  exclude: [build/**]
  errors:
    uri_has_not_been_generated: ignore
    undefined_getter: ignore  
